{% set version = "2.0.9" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-nlmixr2extra
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/nlmixr2extra_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/nlmixr2extra/nlmixr2extra_{{ version }}.tar.gz
  sha256: 858dcfedd11676c944934255528828ed67c8726736e67ca82c74ab0f2e4a9194

build:
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'           # [win]
    - '*/Rblas.dll'       # [win]
    - '*/Rlapack.dll'     # [win]

requirements:
  build:
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
    - {{ compiler('c') }}          # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ compiler('cxx') }}        # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}sed               # [win]
    - {{ posix }}grep              # [win]
    - {{ posix }}autoconf
    - {{ posix }}automake          # [not win]
    - {{ posix }}automake-wrapper  # [win]
    - {{ posix }}pkg-config
    - {{ posix }}make
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - libgomp                      # [linux]
    - llvm-openmp                  # [osx]
  host:
    - r-base
    - r-rcpp
    - r-rcpparmadillo
    - r-checkmate
    - r-cli >=3.4.0
    - r-crayon
    - r-data.table
    - r-digest
    - r-ggplot2
    - r-ggtext
    - r-lotri
    - r-nlme
    - r-nlmixr2est >=2.1.1
    - r-rxode2 >=2.0.10
    - r-symengine
    - libblas
    - liblapack
  run:
    - r-base
    - {{ native }}gcc-libs           # [win]
    - {{ native }}libwinpthread-git  # [win]
    - r-rcpp
    - r-rcpparmadillo
    - r-checkmate
    - r-cli >=3.4.0
    - r-crayon
    - r-data.table
    - r-digest
    - r-ggplot2
    - r-ggtext
    - r-lotri
    - r-nlme
    - r-nlmixr2est >=2.1.1
    - r-rxode2 >=2.0.10
    - r-symengine

test:
  commands:
    - $R -e "library('nlmixr2extra')"           # [not win]
    - "\"%R%\" -e \"library('nlmixr2extra')\""  # [win]

about:
  home: https://nlmixr2.github.io/nlmixr2extra/
  dev_url: https://github.com/nlmixr2/nlmixr2extra/
  license: GPL-3.0-or-later
  summary: Fit and compare nonlinear mixed-effects models in differential equations with flexible dosing information commonly seen in pharmacokinetics and pharmacodynamics (Almquist, Leander, and Jirstrand 2015 <doi:10.1007/s10928-015-9409-1>). Differential equation solving is by compiled C code provided in the 'rxode2'
    package (Wang, Hallow, and James 2015 <doi:10.1002/psp4.12052>). This package is for support functions like preconditioned fits <doi:10.1208/s12248-016-9866-5>, boostrap and stepwise covariate selection.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: nlmixr2extra
# Title: Nonlinear Mixed Effects Models in Population PK/PD, Extra Support Functions
# Version: 2.0.8
# Authors@R: c( person("Matthew", "Fidler", email="matthew.fidler@gmail.com", role = c("aut", "cre"), comment = c(ORCID = "0000-0001-8538-6691")), person("Vipul", "Mann",email="vm2583@columbia.edu", role = "aut"), person("Vishal", "Sarsani", email="vsarsani@umass.edu", comment=c(ORCID = "0000-0002-9272-3438"), role="aut"), person("Christian", "Bartels", email="christian.bartels@novartis.com", role="ctb") )
# Maintainer: Matthew Fidler <matthew.fidler@gmail.com>
# Description: Fit and compare nonlinear mixed-effects models in differential equations with flexible dosing information commonly seen in pharmacokinetics and pharmacodynamics (Almquist, Leander, and Jirstrand 2015 <doi:10.1007/s10928-015-9409-1>). Differential equation solving is by compiled C code provided in the 'rxode2' package (Wang, Hallow, and James 2015 <doi:10.1002/psp4.12052>). This package is for support functions like preconditioned fits <doi:10.1208/s12248-016-9866-5>, boostrap and stepwise covariate selection.
# Depends: R (>= 4.0)
# License: GPL (>= 3)
# URL: https://nlmixr2.github.io/nlmixr2extra/, https://github.com/nlmixr2/nlmixr2extra/
# BugReports: https://github.com/nlmixr2/nlmixr2extra/issues/
# Imports: checkmate, cli (>= 3.4.0), crayon, data.table, digest, ggplot2, ggtext, lotri, nlme, nlmixr2est (>= 2.1.1), Rcpp, rxode2 (>= 2.0.10), stats, symengine, utils
# Suggests: brms, nlmixr2data, testthat (>= 3.0.0), withr, dplyr, devtools
# LinkingTo: Rcpp, RcppArmadillo
# Biarch: true
# Config/testthat/edition: 3
# Encoding: UTF-8
# NeedsCompilation: yes
# RoxygenNote: 7.2.1
# LazyData: true
# Packaged: 2022-10-22 15:12:13 UTC; matt
# Author: Matthew Fidler [aut, cre] (<https://orcid.org/0000-0001-8538-6691>), Vipul Mann [aut], Vishal Sarsani [aut] (<https://orcid.org/0000-0002-9272-3438>), Christian Bartels [ctb]
# Repository: CRAN
# Date/Publication: 2022-10-22 22:32:34 UTC
